global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Go 应用监控
  - job_name: 'go-template-apps'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'host.docker.internal:8080'  # 默认应用端口
        - 'host.docker.internal:8081'  # 其他应用端口
        - 'host.docker.internal:8082'  # 更多应用端口
    scrape_interval: 5s
    scrape_timeout: 3s

  # MySQL 监控 (需要额外的 mysqld_exporter)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysqld-exporter:9104']

  # Redis 监控 (需要额外的 redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node Exporter 监控 (系统指标)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# 告警规则配置
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
