apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.37.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

  # Jaeger 数据源 (如果需要在Grafana中查看Jaeger数据)
  # - name: Jaeger
  #   type: jaeger
  #   access: proxy
  #   orgId: 1
  #   url: http://jaeger:16686
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: true
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: 'loki'
